services:
  reactor-backend:
    build: .
    container_name: reactor-backend
    ports:
      - "${PORT:-8080}:8080"
      - "5679:5679"  # Debug port
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - DEBUG=${DEBUG:-true}
      - RELOADER=${RELOADER:-true}
      - DB_PATH=${DB_PATH:-users.db}
      - DEFAULT_ADMIN_USERNAME=${DEFAULT_ADMIN_USERNAME:-admin}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD:-admin123}
      - SESSION_EXPIRY_HOURS=${SESSION_EXPIRY_HOURS:-24}
      - TOKEN_LENGTH=${TOKEN_LENGTH:-32}
      - DEBUG_PYTHON=${DEBUG_PYTHON:-false}
      - DEBUG_WAIT=${DEBUG_WAIT:-false}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 